// <auto-generated />
using Core.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Core.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180228094421_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Core.DataAccess.DbEntities.EmployeeAttendance", b =>
                {
                    b.Property<long?>("EmployeeDetailId");

                    b.Property<long>("EmployeeAttendanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("InTime");

                    b.Property<DateTime?>("OutTime");

                    b.Property<string>("TotalWorkTime");

                    b.HasKey("EmployeeDetailId");

                    b.HasAlternateKey("EmployeeAttendanceId");

                    b.ToTable("EmployeeAttendance");
                });

            modelBuilder.Entity("Core.DataAccess.DbEntities.EmployeeDetail", b =>
                {
                    b.Property<long>("EmployeeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("EmployeeName");

                    b.HasKey("EmployeeDetailId");

                    b.ToTable("EmployeeDetail");
                });

            modelBuilder.Entity("Core.DataAccess.DbEntities.EmployeeAttendance", b =>
                {
                    b.HasOne("Core.DataAccess.DbEntities.EmployeeDetail", "EmployeeDetail")
                        .WithMany()
                        .HasForeignKey("EmployeeDetailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
